version: "5"


services:
  backend:
    build:
      context: ./backend/
    ports:
      - "8008:8008"
    expose:
      - 8008
    environment:
      - DOCKER=1
    depends_on:
      - db
  
  db:
    image: postgres:15-alpine
    ports:
      - "5430:5430"
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=dnevnik_db
  
  frontend:
    build: 
      context: ./frontend/
    ports:
      - "8888:8888"
    expose:
      - 8888
    depends_on:
      - backend
